### ISSUE TITLE
同じ文字を複数個含む単語を入力したときの表示について

### ISSUE THREAD

**Issue by kzkzoomin** [plumchloride/tango#10]
開発おつかれさまです。同じゲームでも日本語だとここまで難易度が上がるのかと驚きました。
以下、バグというか仕様の改善提案です。

**バグの説明**
同じ文字を複数使う単語を入力したが、正解にはその文字が複数含まれていないとき、灰色になるべき文字が黄色になるが、灰色になるようにしてほしい。
（本家wordleでは正解に当該の文字が複数使われてない場合は、このような場合は灰色になっていたと記憶しています）

例えば、下記スクリーンショットでいうと、4回目「トウキョウ」の２文字目の「ウ」は黄色になっていますが、灰色にならないとウが複数出てくるものと誤解を生むと思います。

（※以下画像では一応ネタバレに配慮して６回目以降マスキングしています）
<img width="587" alt="スクリーンショット 2022-01-29 4 51 35" src="https://user-images.githubusercontent.com/55911955/151613787-d51aee7e-c529-4458-ab70-5e128c70b492.png">

**Desktop (以下の項目を入力してください。):**
 - OS: macOS Big Sur 11.6.1
 - Browser: Chrome
 - Version: 97.0.4692.99

**Comment by plumchloride** [comment]
報告ありがとうございます！
本家Wordleではそのような仕様になっているのですね。確かにそちらの方が理解しやすいと思うのでそのように変更したいと思います。

**Comment by plumchloride** [comment]
https://github.com/plumchloride/tango/commit/3ff7dc156a6172a5486f5ae4b23c1dabe2865885
https://github.com/plumchloride/tango/commit/3ff7dc156a6172a5486f5ae4b23c1dabe2865885
対応遅れてすみません。上記二つのコミットにより変更を完了しました。
