### ISSUE TITLE
タイルの色の動作に問題がある

### ISSUE THREAD

**Issue by SadColor** [plumchloride/tango#11]
日本語が下手ですみません

**バグの説明**
タイルの色は不正確な情報を伝える可能性があります

**発生の状況**
問題の単語にある文字が1つ入る場合、その文字が2つ以上入る単語で答えると、その文字のタイルは全部色が変わります
なので、タイルの色によると問題の単語はその文字が2つ以上入っているように見えます

**期待される動作**
問題の単語にはその文字が1つしか入らないので、その文字のタイルは1つだけ色が変わるはずなのです

**スクリーンショット**
![image](https://user-images.githubusercontent.com/60848907/151603887-a7dcf241-2c72-4a6a-9f9c-3164e958cfe6.png)
![image](https://user-images.githubusercontent.com/60848907/151606512-c88eda83-7444-498d-b5d7-4c3d40dcaae2.png)

原作Wordleと異なる動作なのです (Eに注意してください)
![image](https://user-images.githubusercontent.com/60848907/151603985-1864757f-55d9-4093-b3b6-92cad9f59564.png)

**Desktop (以下の項目を入力してください。):**
 - OS: Windows 10
 - Browser Firefox Developer Edition
 - Version 97.0b8

**Comment by plumchloride** [comment]
報告ありがとうございます！
本家Wordleではそのような仕様になっているのですね。確かにそちらの方が理解しやすいと思うのでそのように変更したいと思います。

**Comment by plumchloride** [comment]
https://github.com/plumchloride/tango/commit/3ff7dc156a6172a5486f5ae4b23c1dabe2865885
https://github.com/plumchloride/tango/commit/3ff7dc156a6172a5486f5ae4b23c1dabe2865885
対応遅れてすみません。上記二つのコミットにより変更を完了しました。
