### ISSUE TITLE
不正解時の共有

### ISSUE THREAD

**Issue by west321kei** [plumchloride/tango#16]
**バグの説明**
10回とも不正解だった場合の成績が 10/10 となるが、
これは10回目に正解だった場合の成績。

**期待される動作**
オリジナル版では6回とも不正解だった場合 X/6 という成績になる。

**Comment by plumchloride** [comment]
共有ありがとうございます。
確認しました。そちらの方が確かによろしいですね。次のアップデート時に変更します

**Comment by plumchloride** [comment]
[fb9e905](https://github.com/plumchloride/tango/commit/b23b189bfadde21db5b144afa596d86488126600)
上記コミットにて修正しました。報告ありがとうございます
