### ISSUE TITLE
Delボタンの挙動

### ISSUE THREAD

**Issue by west321kei** [plumchloride/tango#25]
今の挙動で誤入力が多いので以下の挙動を提案します。

1. カーソル位置に文字が入っているとき
　　→カーソル位置の文字を消す
　　　（通常のテキストエディタのDelキーの挙動）
2. カーソル位置に文字が入っていない＆カーソル位置が1文字目以外のとき
　　→カーソル位置の1文字前の文字を消し、カーソル位置を1文字前に移動
　　　（テキストエディタのBackSpaceキーの挙動）

**Comment by plumchloride** [comment]
提案ありがとうございます！！
Delキーの挙動に関してはかねてより不満がありどうした物かと考えていました。
そのような動作の方が直感的で分かり安いので、次回のアップデート時にそちらの機能に変更します！

**Comment by plumchloride** [comment]
https://github.com/plumchloride/tango/commit/a14a70b07a7a7df2823b558aa18102feed57cfa2
こちらのコミットで修正しました！
報告ありがとうございます。
