### ISSUE TITLE
バグ

### ISSUE THREAD

**Issue by ktka0906** [plumchloride/tango#26]
![Screenshot_20220216-092002](https://user-images.githubusercontent.com/99773337/154172861-4b37d777-1262-4dcb-8341-62bdded0fe7a.png)
**バグの説明**
リスト内にあるはずの単語を入力したが、「ひらがな、カタカナで5文字以上…」といった内容の警告がでた。
その試行は行ったものとされるが、結果は反映されない。
次の単語を試すと前に入力した単語は消えてしまい、試行回数のみ消費される。

**発生の状況**
発生時の操作
1. 単語入力途中でスマホのキーボード操作

**期待される動作**
期待したことが明確に、かつ簡潔に書かれていること。
エラーの原因の解明
可能なら第26回の問題を1回目の試行からやり直したい。

**スクリーンショット**
該当する場合は、問題を説明するためにスクリーンショットを追加してください。
追加済み

**Smartphone (以下の項目を入力してください。):**
 - Device: XPERIA SO-021
 - OS: android
 - Browser google chrome
 - Version 不明

**追加情報**
その他、問題についてなにかあれば、ここに追加してください。
ブラウザの更新、スマホの再起動は試したが効果無し。

**Comment by plumchloride** [comment]
反応遅れて申し訳ございません。報告ありがとうございます。
https://github.com/plumchloride/tango/commit/b6b168eefe00b2a24657d6af2b06d5ba09eb4739
こちらの修正で対応しましたが、原因として
デバイスに残っているキャッシュが正常に削除されない影響で、一部コードのみアップデートされ、コード間のバージョンが異なる影響でエラーが発生した
といった状況です。

解決策として、デバイスに残っているCookieではなくキャッシュを設定の欄から削除することがあげられます。
画面左上残り候補数の後ろに続く表記が”ーーー”ではなく数字に変わっていれば正常にアップデートが行われています。

第26回の問題を1回目の試行からやり直したい問題に関しては戦歴に残らない手段ですが、シークレットモードで「ことのはたんご」を開くと履歴が残っていない状況でプレイが出来ると思います。

対応遅れて申し訳ございません。Web開発といった都合上すべての端末での動作確認が出来ず申し訳ございません。
