### ISSUE TITLE
共有用の残り候補数

### ISSUE THREAD

**Issue by west321kei** [plumchloride/tango#29]
NaN とは Not a Number の略です。
例えば 3÷0 の答えは無限大で数値ではないので NaN ですが
50000 など単に大きな数値の場合は NaN ではありません。
例えば3桁以内に収めたいならば、100以上の場合は >99 と表記するほうが適切と考えます。

**Comment by plumchloride** [comment]
報告ありがとうございます！

残り候補数にて表示されるNaNはご存じの通り「Not a Number」です。
Web開発の都合上、コードのバージョンに差が出ており、残り候補数を正常に取得出来なかった場合に現れます。
正常な動作時には恐らく30000などの大きな数値が出力されるはずです。

コードのバージョンが異なるバグは、次回のアップデートにて内部構造を変えることで修正する予定です。

ご迷惑をおかけして申し訳ございません。わざわざ報告ありがとうございます。
