### ISSUE TITLE
ことのはたんごのバグ

### ISSUE THREAD

**Issue by pipi5315** [plumchloride/tango#43]
![030B427C-AA47-4AD3-8802-BE2FEA28CC0E](https://user-images.githubusercontent.com/100954461/156796182-a6f7e0d1-7745-41c2-b9bd-7ce0da01c444.png)

**バグの説明**
途中で予測単語が変わった

**発生の状況**
発生時の操作
1. '...' に移動
2. '...' をクリック
3. スクロールダウンして '......' をクリック
4. エラー

**期待される動作**
期待したことが明確に、かつ簡潔に書かれていること。

**スクリーンショット**
該当する場合は、問題を説明するためにスクリーンショットを追加してください。

**Desktop (以下の項目を入力してください。):**
 - OS: [例 iOS]
 - Browser [例 chrome, safari]
 - Version [例 22]

**Smartphone (以下の項目を入力してください。):**
 - Device: [例 iPhone6]
 - OS: [例 iOS8.1]
 - Browser [例 stock browser, safari]
 - Version [例 22]

**追加情報**
その他、問題についてなにかあれば、ここに追加してください。

**Comment by plumchloride** [comment]
報告ありがとうございます。
ご迷惑をおかけしました。前半の回答と後半の回答時にバージョンによる差が出ておりこのような結果になったと思われます。

前半のたんごは正常では出題されない予定でして答えは「指定券：シテイケン」もしくは入力していただいた「支配権・支配圏：シハイケン」の二つとなっています。

後半のたんごに関しては正常に出題される予定のたんごのためもしよろしければシークレットモードなどで取り組んでいただけると幸いです。
ご迷惑をおかけして申し訳ございませんでした。もしよろしければ今後ともよろしくお願いします。
