### ISSUE TITLE
バグですと表示されてプレイできない

### ISSUE THREAD

**Issue by umi** [plumchloride/tango#51]
**バグの説明**
バグですと表示されてプレイできない

**発生の状況**
発生時の操作
1. '[ページ](https://plum-chloride.jp/kotonoha-tango/index.html)' を開く
2. バグですと表示されてプレイ出来ない

**期待される動作**
新しい問題が出題される

**スクリーンショット**
![image](https://user-images.githubusercontent.com/380145/160719647-d1160e16-ebb8-47a0-a687-d9ae6d8e4af8.png)
![image](https://user-images.githubusercontent.com/380145/160720082-02b820a0-bcd3-4604-848e-582386ff99d0.png)

**Desktop (以下の項目を入力してください。):**
 - OS: Win10
 - Browser: Chrome
 - Version: 99.0.4844.84

**追加情報**
ヨーロッパからのアクセスなのでタイムゾーンが違います

**Comment by umi** [comment]
再度アクセスしたところ現在はなぜか改善してプレイ出来ています

**Comment by plumchloride** [comment]
報告ありがとうございます。
JavaScriptの new Date()周りの挙動をあまり理解していないため、サマータイム等の影響がどれほど出ているかが不明確で申し訳ございません。

今後手が空いた際にエラーをはかない様に修正できるか取り組んでみます。
