### ISSUE TITLE
残り候補数の表示がおかしい

### ISSUE THREAD

**Issue by hiroshi-iteya** [plumchloride/tango#57]
**バグの説明**
残り候補数の表示がおかしい

**発生の状況**
（第99回プレイ）
1. 回答にマージャンと入力
2. 回答にシュキョウと入力
3. 回答にホンチョウと入力
4. 残り候補数が１となる。が、センチョウなどの候補に適合する答えを入力しても正解にならない。

**期待される動作**
残り候補数が正確に表示されること

**スクリーンショット**
![スクリーンショット 2022-04-30 20 32 27](https://user-images.githubusercontent.com/24842457/166103910-99138654-b845-481c-98dc-5af4f265c8b3.png)

![IMG_1E4CC7D8232B-1](https://user-images.githubusercontent.com/24842457/166103832-260bc5ed-e98b-4862-a2ee-a22cf310d80a.jpeg)

**Desktop (以下の項目を入力してください。):**
 - OS: macOS
 - Browser  chrome 
 - Version 100.0.4896.127

**Smartphone (以下の項目を入力してください。):*

*

**追加情報**
その他、問題についてなにかあれば、ここに追加してください。

**Comment by plumchloride** [comment]
報告ありがとうございます。
２試行目「シュキョウ」における「キ」が黄色評価を下されているため、該当の文字が１文字目に入り、「キンチョウ」が正答の単語となります。
