### ISSUE TITLE
残り候補数は0になりました

### ISSUE THREAD

**Issue by agenga0320** [plumchloride/tango#60]
**バグの説明**
バグの内容を明確かつ簡潔に説明すること。

**発生の状況**
エラー

**期待される動作**
"さんかよう"を入力する前に残り候補数は1です。
"さんかよう"を入力する後で残り候補数は0になりました。

**スクリーンショット**
![Screenshot_20221226-002221](https://user-images.githubusercontent.com/45278205/209473819-0c306276-70d5-46db-9690-651fa28b2f41.png)

**Smartphone (以下の項目を入力してください。):**
 - Device: Google pixel 5
 - OS: Android 
 - Browser : Google chrome
 - Version [例 22]

**追加情報**

**Comment by plumchloride** [comment]
ご迷惑をおかけして申し訳ございません。
正答の単語が単語検証用の辞書に登録されていなかったため発生したエラーとなっています。
回答が完了していない場合はリロードすることで正常に単語を入力出来るようになります。完了している場合でも記録をロールバックすることが可能です。  
ウェブアプリケーションに入るとその旨が伝えられると思います。

詳しくは下記ツイートを参照してください。
https://twitter.com/plum_chloride/status/1607150126023471106?s=20&t=OTr8iDitRYSyPG3pLo_04g

修正コミット：
https://github.com/plumchloride/tango/commit/46c74c3bab5f0f82dbb37d121d75232c97c69127
