### ISSUE TITLE
海外タイムゾーンに対応していない？

### ISSUE THREAD

**Issue by umi** [plumchloride/tango#9]
**バグの説明**
今日の単語　残り時間が0（JSTベース）になっても画面が切り替わらない
海外タイムゾーンだから？（日本は1/28だがこちらはまだ1/27）

**発生の状況**
発生時の操作
1. 'https://plum-chloride.jp/kotonoha-tango/index.html' に移動
2. 前日の正解画面が表示される（が、なにかおかしい。もしかしたら次の答えが表示されている？）

**期待される動作**
残り時間が０になったら新しい問題に挑戦出来る

**スクリーンショット**
![image](https://user-images.githubusercontent.com/380145/151430951-e445ab46-0c1d-4772-a518-bb7478736ac7.png)

**Desktop (以下の項目を入力してください。):**
 - OS: Windows10
 - Browser chrome
 - Version 97.0.4692.99

**Comment by plumchloride** [comment]
バグ報告ありがとうございます！！
ゲームリリースから経過日数を取得する箇所にてタイムゾーンが異なると第〇回の表記が異なる（一日前の値になる）現象を発見し、修正しました。（現在GitHubのリポジトリが汚いため具体的なコミットは並記できず申し訳ございません。）

```JavaScript;some.js
// 改善前
const  First_Day = new Date(new Date("2022/1/21").getTime()+((new Date().getTimezoneOffset() + (9 * 60)) * 60 * 1000));
jst = new Date(Date.now() + ((new Date().getTimezoneOffset() + (9 * 60)) * 60 * 1000));
timestamp = jst - First_Day;
pass_day =  Math.floor(timestamp/(24 * 60 * 60 * 1000));
// 改善後
jst = new Date(Date.now() + ((new Date().getTimezoneOffset() + (9 * 60)) * 60 * 1000));
const First_Day = Date.UTC(2022,1,21);
const Now_Day = Date.UTC(jst.getFullYear(),jst.getMonth()+1,jst.getDate());
timestamp = Now_Day - First_Day;
pass_day =  Math.floor(timestamp/(24 * 60 * 60 * 1000));

```

改善前では現地時刻のリリース日より現在の日本時刻を引くことでゲームの経過日数を図っていました。これは誤りで、改善後では「UTCのリリース日」より「現在の日本時刻より取得した日付を用いて取得するUTCの時間」を引くことで日本時刻基準で経過日数の表示が出来る様になりました。

このバグにより、下記現象が起きこのような事態になったと思われます。
- ウェブストレージより値を取得
- 前日のデータを取得する際にpass_day値が原因で当日のデータと勘違いをしクリア判定を出力
- 後ろの回答画面には前回の回答時の単語が出力
- クリア判定より当日の単語の答えが出力

といった流れです。

この度はご迷惑をおかけしました。結果的に本日の単語が見えてしまっている点謝罪いたします。

念のため日付の変更を確認してからissueを閉じます（こちらで確認いたします）。
また変更に関してウェブサイトの反映には数分程度かかる場合がありますご迷惑をおかけします。

**Comment by plumchloride** [comment]
対応完了のためクローズ
